services:
  - name: nginx_service
    image: nginx:latest
journeys:
  - name: get index
    steps:
      - curl http://nginx_service
stages:
  - name: default
    clients: 1
    duration: 1s
    disk_corruption: 5%
    network_failure: 23.4%
    full_outage: 2.01%
